services:
  # Servicio InfluxDB
  influxdb:
    image: influxdb:1.8 # Se recomienda la versión 1.x para una integración más directa con k6
    container_name: influxdb-k6
    ports:
      - "8086:8086" # Puerto predeterminado para la API de InfluxDB
    volumes:
      - influxdb_data:/var/lib/influxdb # Persistencia de datos de InfluxDB
    environment:
      # Variables de entorno para InfluxDB (versión 1.x)
      - INFLUXDB_DB=k6_metrics # Nombre de la base de datos que usará k6
      - INFLUXDB_ADMIN_USER=admin # Usuario administrador (opcional, pero buena práctica)
      - INFLUXDB_ADMIN_PASSWORD=adminpassword # Contraseña del usuario administrador
      - INFLUXDB_HTTP_AUTH_ENABLED=true # Habilitar autenticación HTTP (importante para k6)
    restart: unless-stopped # Asegura que el servicio se reinicie si el contenedor falla


  # Servicio Grafana
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana-k6
    ports:
      - "3000:3000" # Puerto predeterminado para Grafana
    volumes:
      - grafana_data:/var/lib/grafana # Persistencia de datos de Grafana (dashboards, config)
      # Montamos el directorio de provisioning para configurar datasources y dashboards automáticamente
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin # ¡Cambia esto después del primer inicio de sesión!
      - K6_INFLUXDB_DATABASE=k6_metrics
      # Para versiones más recientes, puedes especificar plugins
      #- GF_INSTALL_PLUGINS=grafana-influxdb-datasource
    restart: unless-stopped

  # Servicio k6 (NO se levantará con `docker compose up -d`. Se ejecutará manualmente cuando sea necesario)
  # Este servicio está aquí solo para definir la configuración de la imagen y volúmenes.
  k6:
    image: grafana/k6:latest
    container_name: k6-runner # Este nombre será efímero, puedes dejarlo o cambiarlo
    # Volúmenes para montar el script de k6 y opcionalmente otros archivos (ej. data.json)
    volumes:
      - ./k6:/k6 # Monta tu carpeta local 'k6' en '/k6' dentro del contenedor
    environment:
      # Configuración de k6 para enviar métricas a InfluxDB
      # 'influxdb' es el nombre del servicio InfluxDB en Docker Compose
      - K6_OUT=influxdb=http://influxdb:8086/k6_metrics
      - K6_INFLUXDB_USERNAME=admin # Si InfluxDB requiere autenticación
      - K6_INFLUXDB_PASSWORD=adminpassword # Si InfluxDB requiere autenticación
    # `entrypoint` se puede usar para especificar el comando por defecto,
    # pero para k6 es mejor ejecutarlo explícitamente con `docker compose run`
    # entrypoint: k6 run /k6/script.js

# Volúmenes nombrados para persistencia de datos
volumes:
  influxdb_data:
  grafana_data: