services:
  influxdb:
    image: influxdb:1.8 # Especifica la versión de InfluxDB
    networks:
      - k6_net       # Usa nombres de red consistentes y descriptivos
      - grafana_net
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6                 # Base de datos a crear en InfluxDB
      - INFLUXDB_ADMIN_USER=admin      # Usuario administrador
      - INFLUXDB_ADMIN_PASSWORD=adminpass  # Contraseña del administrador
    volumes: 
    - influxdb_data:/var/lib/influxdb  # Persiste los datos de InfluxDB
 
    command: 
      influxd -config /etc/influxdb/influxdb.conf

  grafana:
    image: grafana/grafana:latest        # Usa la última versión estable
    networks:
      - grafana_net
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Contraseña del administrador de Grafana
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - influxdb                          # Grafana depende de InfluxDB

  k6:
    image: grafana/k6:latest
    networks:
      - k6_net                          # k6 se conecta a la red k6
    depends_on:
      - influxdb
    command: >
      run
      --out influxdb=http://admin:adminpass@influxdb:8086/k6
      -e TYPE_TEST=loadTest
      /scripts/k6_register_users.js
    volumes:
      - ./scripts:/scripts
    ports:
      - "6565:6565"                     # Exponer el puerto de k6 (opcional)

networks:
  k6_net:
    name: k6_net
  grafana_net:
    name: grafana_net

volumes:
  influxdb_data:                       # Define el volumen para InfluxDB
    driver: local
#      /scripts/k6_register_users.js
#      /scripts/k6_full_user_flow_test.js
#      /scripts/smoke-test.js