services:
  influxdb:
    image: influxdb:1.8
    networks:
      - k6_net
      - grafana_net
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpass
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana_net
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb

  k6:
    image: grafana/k6:latest
    networks:
      - k6_net
    depends_on:
      - influxdb
    command: >
      run
      --out influxdb=http://admin:adminpass@influxdb:8086/k6
      /scripts/k6_minimal.js
    volumes:
      - ./scripts:/scripts

networks:
  k6_net:
    name: k6_net
  grafana_net:
    name: grafana_net

volumes:
  influxdb_data:
    driver: local