services:
  influxdb:
    image: influxdb:1.8
    networks:
      - k6_net
      - grafana_net
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpass
    volumes: []
    command:
      influxd -config /etc/influxdb/influxdb.conf

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana_net
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - influxdb

  k6:
    image: grafana/k6:latest
    networks:
      - k6_net
    depends_on:
      - influxdb
    environment:
      - K6_SCRIPT_TO_RUN=/scripts/smoke-test.js # Valor por defecto
      - TYPE_TEST=loadTest # Tu variable existente
    command: >
      run
      --out influxdb=http://admin:adminpass@influxdb:8086/k6
      -e TYPE_TEST=loadTest
      ${K6_SCRIPT_TO_RUN} # <--- Usamos la variable de entorno aquí
    volumes:
      - ./scripts:/scripts
    ports:
      - "6565:6565"

networks:
  k6_net:
    name: k6_net
  grafana_net:
    name: grafana_net

volumes:
  influxdb_data:
    driver: local