{
 "title": "K6 Stress Test Dashboard",
 "panels": [
  {
   "title": "Authenticate Duration",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "measurement": "authenticate_duration",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] }
     ],
     "select": [
      [
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "InfoUser Duration",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "measurement": "infoUser_duration",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] }
     ],
     "select": [
      [
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UserAccessToken Duration",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "measurement": "getUserAccessToken_duration",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] }
     ],
     "select": [
      [
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LiveSession Duration",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "measurement": "liveSession_duration",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] }
     ],
     "select": [
      [
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NewSession Duration",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 24, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "measurement": "newSession_duration",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] }
     ],
     "select": [
      [
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    }
   ]
  }
 ]
}