{
 "title": "new k6 dashboard",
 "description": "k6.io dashboard",
 "tags": [
  "k6",
  "load testing"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Measurement",
    "query": "http_req_duration,http_req_blocked,http_req_connecting,http_req_looking_up,http_req_receiving,http_req_sending,http_req_waiting"
   },
   {
    "name": "URL",
    "label": "URL",
    "query": "SHOW TAG VALUES WITH KEY = \"name\""
   }
  ]
 },
 "panels": [
  { "title": "K6 Test overview (all URLs)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virtual User",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "Active VUs",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Requests per Second",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Num Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_req_failed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Checks Per Second",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "alias": "$tag_check",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "check" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "checks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$Measurement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "Measurement" },
  {
   "title": "http_req_duration (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^http_req_duration$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^*$/" }
     ]
    },
    {
     "alias": "p95",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^http_req_duration$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^*$/" }
     ]
    },
    {
     "alias": "p90",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^http_req_duration$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^*$/" }
     ]
    },
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^http_req_duration$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  },
  {
   "title": "http_req_duration (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (count)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (min)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (med)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" }
     ]
    }
   ]
  },
  {
   "title": "http_req_duration (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "measurement": "/^http_req_duration$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (max)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (mean)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (p95)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" }
     ]
    }
   ]
  },
  {
   "title": "Groups",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT count(\"value\"), sum(\"value\") as \"Success Count\",min(\"value\"), median(\"value\"), max(\"value\"), mean(\"value\"), percentile(\"value\", 95) FROM /^$Measurement$/ WHERE $timeFilter GROUP BY \"group\", \"method\", \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests Success and Failure Stats",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT sum(\"value\") as \"Success Count\", count(\"value\") as Total FROM \"checks\" WHERE $timeFilter GROUP BY \"group\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "URLs and latencies",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  }
 ]
}